### ISSUE TITLE
need option for network drive or rclone

### ISSUE THREAD

**Issue by technickal1** [sbsos/hotplotterclient#7]

**Comment by sbsos** [comment]
Are you wanting functionality to be able to show attached network drives to show up in Destination Drives for plotting?

If so, it's something I did have in mind. I have a release coming in the next few days for the server, and then I planned on starting on something similar to that.

**Comment by technickal1** [comment]
Yes, having the option for a network drive is where I transfer my plots
now, not on the same machine.

**Comment by sbsos** [comment]
Sounds good. I'll put this to the top priority, and start in on it this week. Got a few ideas in mind.

**Comment by sbsos** [comment]
In the latest 4.1 release, it should detect network attached drives easier, for Windows and Linux. If it's still not showing up, please let me know. 

I tested Samba mounted drives, and TrueNAS Pool.
